export enum Permissions {
    INDEX_AGENT = 'INDEX_AGENT',
    EXPORT_AGENT = 'EXPORT_AGENT',
    SHOW_AGENT = 'SHOW_AGENT',
    STORE_AGENT = 'STORE_AGENT',
    UPDATE_AGENT = 'UPDATE_AGENT',
    DELETE_AGENT = 'DELETE_AGENT',
    UPLOAD_AGENT = 'UPLOAD_AGENT',

    INDEX_AGGREGATOR = 'INDEX_AGGREGATOR',
    EXPORT_AGGREGATOR = 'EXPORT_AGGREGATOR',
    SHOW_AGGREGATOR = 'SHOW_AGGREGATOR',
    STORE_AGGREGATOR = 'STORE_AGGREGATOR',
    UPDATE_AGGREGATOR = 'UPDATE_AGGREGATOR',
    DELETE_AGGREGATOR = 'DELETE_AGGREGATOR',

    INDEX_COMMISSION_PLAN = 'INDEX_COMMISSION_PLAN',
    STORE_COMMISSION_PLAN = 'STORE_COMMISSION_PLAN',
    UPDATE_COMMISSION_PLAN = 'UPDATE_COMMISSION_PLAN',
    EXPORT_COMMISSION_PLAN = 'EXPORT_COMMISSION_PLAN',
    DELETE_COMMISSION_PLAN = 'DELETE_COMMISSION_PLAN',

    UPDATE_SUPPLIER =  'UPDATE_SUPPLIER',
    UPDATE_CATEGORY = 'UPDATE_CATEGORY',
    UPDATE_PRODUCT = 'UPDATE_PRODUCT',

    INDEX_CREDIT_REQUEST = 'INDEX_CREDIT_REQUEST',
    EXPORT_CREDIT_REQUEST = 'EXPORT_CREDIT_REQUEST',
    CANCEL_CREDIT_REQUEST = 'CANCEL_CREDIT_REQUEST',
    SHOW_CREDIT_REQUEST = 'SHOW_CREDIT_REQUEST',



    INDEX_CREDIT_REQUEST_PRODUCT =  'INDEX_CREDIT_REQUEST_PRODUCT',
    'EXPORT_CREDIT_REQUEST_PRODUCT' = 'EXPORT_CREDIT_REQUEST_PRODUCT',

    SHOW_SYSTEM_STATS = 'SHOW_SYSTEM_STATS',
    SHOW_WHOLESALER_STATS = 'SHOW_WHOLESALER_STATS',
    SHOW_AGGREGATOR_STATS = 'SHOW_AGGREGATOR_STATS',

    INDEX_LENDER = 'INDEX_LENDER',
    SHOW_LENDER = 'SHOW_LENDER',
    STORE_LENDER = 'STORE_LENDER',
    UPDATE_LENDER = 'UPDATE_LENDER',
    EXPORT_LENDER = 'EXPORT_LENDER',
    DELETE_LENDER = 'DELETE_LENDER',

    INDEX_LENDER_PROVISION = 'INDEX_LENDER_PROVISION',
    EXPORT_LENDER_PROVISION = 'EXPORT_LENDER_PROVISION',
    STORE_LENDER_PROVISION = 'STORE_LENDER_PROVISION',
    SHOW_LENDER_PROVISION = 'SHOW_LENDER_PROVISION',
    VALIDATE_LENDER_PROVISION = 'VALIDATE_LENDER_PROVISION',

    INDEX_LOAN_REQUEST = 'INDEX_LOAN_REQUEST',
    EXPORT_LOAN_REQUEST = 'EXPORT_LOAN_REQUEST',
    STORE_LOAN_REQUEST = 'STORE_LOAN_REQUEST',
    VALIDATE_LOAN_REQUEST = 'VALIDATE_LOAN_REQUEST',
    REPAY_LOAN_REQUEST = 'REPAY_LOAN_REQUEST',
    SHOW_LOAN_REQUEST = 'SHOW_LOAN_REQUEST',

    SHOW_MEDIA = 'SHOW_MEDIA',
    DELETE_MEDIA = 'DELETE_MEDIA',

    INITIATE_NANO_CREDIT = 'INITIATE_NANO_CREDIT',
    VALIDATE_NANO_CREDIT = 'VALIDATE_NANO_CREDIT',

    INDEX_OPERATION = 'INDEX_OPERATION',
    INDEX_ACCOUNT_OPERATION = 'INDEX_ACCOUNT_OPERATION',
    EXPORT_ACCOUNT_OPERATION = 'EXPORT_ACCOUNT_OPERATION',

    STORE_OVERDRAFT_REQUEST = 'STORE_OVERDRAFT_REQUEST',

    INDEX_REFUND_REQUEST = 'INDEX_REFUND_REQUEST',
    EXPORT_REFUND_REQUEST = 'EXPORT_REFUND_REQUEST',
    INITIATE_REFUND_REQUEST = 'INITIATE_REFUND_REQUEST',
    VALIDATE_REFUND_REQUEST = 'VALIDATE_REFUND_REQUEST',
    CANCEL_REFUND_REQUEST = 'CANCEL_REFUND_REQUEST',

    INDEX_WHOLESALER = 'INDEX_WHOLESALER',
    EXPORT_WHOLESALER = 'EXPORT_WHOLESALER',
    SHOW_WHOLESALER = 'SHOW_WHOLESALER',
    STORE_WHOLESALER = 'STORE_WHOLESALER',
    UPDATE_WHOLESALER = 'UPDATE_WHOLESALER',
    DELETE_WHOLESALER = 'DELETE_WHOLESALER',
    BULK_WHOLESALER_SETTINGS = 'BULK_WHOLESALER_SETTINGS',

    INDEX_WHOLESALER_PROVISION = 'INDEX_WHOLESALER_PROVISION',
    EXPORT_WHOLESALER_PROVISION = 'EXPORT_WHOLESALER_PROVISION',
    STORE_WHOLESALER_PROVISION = 'STORE_WHOLESALER_PROVISION',
    SHOW_WHOLESALER_PROVISION = 'SHOW_WHOLESALER_PROVISION',
    VALIDATE_WHOLESALER_PROVISION = 'VALIDATE_WHOLESALER_PROVISION',

    INDEX_CURRENCY_RATE = 'INDEX_CURRENCY_RATE',
    UPDATE_CURRENCY_RATE = 'UPDATE_CURRENCY_RATE',
    STORE_CURRENCY_RATE = 'STORE_CURRENCY_RATE',
    DELETE_CURRENCY_RATE = 'DELETE_CURRENCY_RATE',
    SHOW_CURRENCY_RATE = 'SHOW_CURRENCY_RATE',

    INDEX_VALIDATION_STAGE = 'INDEX_VALIDATION_STAGE',
    STORE_VALIDATION_STAGE = 'STORE_VALIDATION_STAGE',
    SHOW_VALIDATION_STAGE = 'SHOW_VALIDATION_STAGE',
    UPDATE_VALIDATION_STAGE = 'UPDATE_VALIDATION_STAGE',
    DELETE_VALIDATION_STAGE = 'DELETE_VALIDATION_STAGE',


    STORE_CATEGORY = 'STORE_CATEGORY',
    INDEX_CATEGORY = 'INDEX_CATEGORY',
    DELETE_CATEGORY = 'DELETE_CATEGORY',
    SHOW_CATEGORY = 'SHOW_CATEGORY',
    STORE_SUPPLIER = 'STORE_SUPPLIER',
    DELETE_SUPPLIER = 'DELETE_SUPPLIER',
    GET_ALL_SUPPLIER = 'GET_ALL_SUPPLIER',
    STORE_PRODUCT = 'STORE_PRODUCT',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    SHOW_PRODUCT   = 'SHOW_PRODUCT',
    INDEX_PRODUCT = 'INDEX_PRODUCT',

    INDEX_VALIDATION_OPERATION = 'INDEX_VALIDATION_OPERATION',
    STORE_VALIDATION_OPERATION = 'STORE_VALIDATION_OPERATION',
    SHOW_VALIDATION_OPERATION = 'SHOW_VALIDATION_OPERATION',
    UPDATE_VALIDATION_OPERATION = 'UPDATE_VALIDATION_OPERATION',

    ACTIVATE_WHOLESALER_DMA = 'ACTIVATE_WHOLESALER_DMA',
    REFUND_WHOLESALER_DMA = 'REFUND_WHOLESALER_DMA',

    STORE_PRODUCT_BULK = 'STORE_PRODUCT_BULK',

}
